<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="libingxian" name="com.testng.demo.DataProviderDemo" tests="7" failures="1" timestamp="8 Mar 2017 02:33:19 GMT" time="0.016" errors="0">
  <testcase name="testmethod1" time="0.008" classname="com.testng.demo.DataProviderDemo"/>
  <testcase name="testmethod3" time="0.001" classname="com.testng.demo.DataProviderDemo"/>
  <testcase name="testmethod3" time="0.001" classname="com.testng.demo.DataProviderDemo"/>
  <testcase name="testmethod3" time="0.003" classname="com.testng.demo.DataProviderDemo"/>
  <testcase name="testmethod3" time="0.002" classname="com.testng.demo.DataProviderDemo"/>
  <testcase name="testmethod3" time="0.001" classname="com.testng.demo.DataProviderDemo"/>
  <testcase name="testmethod2" time="0.000" classname="com.testng.demo.DataProviderDemo">
    <failure type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:165)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testmethod2 -->
</testsuite> <!-- com.testng.demo.DataProviderDemo -->
